### ISSUE TITLE
add image orientation check

### ISSUE THREAD

**Issue by iverissimo** [gjheij/linescanning#5]
Realized that MP2RAGE I had was in PSR orientation (336x336x265) and code expects image to be RAS (265x336x336).
This is only caught in module 13 in `call_gdhmasking` - when calculating 'outside' mask (line 248) from dilated dura mask and sinus drawn in ITKsnap, they will have different affines...
Because I noticed this, I reoriented the two inversions niftis with a quick script 
```
orig_img = nb.load(input_file)
canonical_img = nb.as_closest_canonical(orig_img)
nb.save(canonical_img, input_file.replace('.nii.gz','RAS_.nii.gz'))
```

and re-ran the pipeline. Then all was fine.
Would be better to have some orientation check in the first modules (maybe in spinoza_qmrimaps?) to avoid this. Can be done by re-orienting the images in the pipeline, or throwing an error so the user knows the orientation should be RAS.

**Comment by gjheij** [comment]
Good point. There's a function [call_reorient](https://github.com/gjheij/linescanning/blob/main/bin/call_reorient) that does what you did. I always run this during the conversion to BIDS so that I don't have to worry about it anymore. Good to have a check in there. 

RAS is especially required for `Nighres`, if you don't use that it's just important all affines are the same.
